### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by ebinum83** [ashisherc/advanced-solidity-lottery-application#6]
ERROR  Failed to compile with 1 errors

 error  in ./node_modules/web3-core-helpers/lib/formatters.js

Module parse failed: Unexpected token (296:20)
You may need an appropriate loader to handle this file type.
|     // If options !== undefined, don't blow out existing data
|     if (options.fromBlock === undefined)
|         options = { ...options, fromBlock: 'latest' };
|     if (options.fromBlock || options.fromBlock === 0)
|         options.fromBlock = inputBlockNumberFormatter(options.fromBlock);

 @ ./node_modules/web3-core-helpers/lib/index.js 24:17-40
 @ ./node_modules/web3-eth/lib/index.js
 @ ./node_modules/web3/lib/index.js
 @ ./src/web3/web3.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server ./src/main.js

I tried to run npm run dev, and it starts building the modules, but stops at:

69% building modules 625/626 modules 1 active ..._modules/inherits/inherits_bro 
94% asset optimization

Any help please........................................................?

**Comment by ashisherc** [comment]
Hey thanks for the issue, but this repo is quite old. A LOT has been changed since this was written. Though you may still be able to use the Solidity contract, I may not be able to update the frontend.
